EdGenius/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('EdGeniusApp.urls')),
]

EdGeniusApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'EdGeniusApp'

urlpatterns = [
    path('',views.Index.as_view(), name='index'),
    path('payment/', views.PaymentGateway.as_view(), name='payment'),
    path('charge/<int:amount>',views.charge, name='charge'),
    path('shomepage/', views.StudentHomeView.as_view(), name='student_home'),
    path('ihomepage/', views.InstructorHomeView.as_view(), name='instructor_home'),
    path('login/', views.LoginInterfaceView.as_view(), name='login'),
    path('logout/', views.LogoutInterfaceView.as_view(), name='logout'),
    path('authorized/', views.AuthorizedView.as_view(), name='authorized'),
    path('signup/', views.signup, name='signup'),
    path('password_reset/', views.PasswordResetInterfaceView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name ='EdGeniusApp/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name ='EdGeniusApp/password_reset_confirm.html', success_url = reverse_lazy("EdGeniusApp:password_reset_complete")),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name ='EdGeniusApp/password_reset_complete.html'), name='password_reset_complete'),
    path('handle_payment_success/', views.handle_payment_success, name='payment_success'),
    path('attendance/<str:course_name>', views.student_attendance, name='student_attendance'),
    path('update_attendance/<str:course_name>', views.update_attendance, name='update_attendance'),
    path('my_courses/', views.my_courses, name='my_courses'),
    path('fetch_attendance/<str:course_name>', views.fetch_attendance, name='fetch_attendance'),
    path('fetchstudent/<str:course_name>', views.fetch_attendance_student, name='fetchstudent'),
    path('grades_provider/<str:course_name>', views.grade_page, name='grades_provider'),
    path('check_student_grades/<str:course_name>', views.CheckStudentGrades.as_view(), name='check_student_grades'),
#    path('check_student_grades/<str:course_name>', views.CheckStudentGrades.as_view(), name='check_grades'),
    path('view_my_grades/<str:course_name>', views.ViewMyGrades.as_view(), name='my_grades'),
    path('view_my_attendance/<str:course_name>', views.ViewMyAttendance.as_view(), name='my_attendance'),
    path('add_course/', views.add_course, name='add_course'),
    path('<slug:course_slug>/add_courseFiles', views.AddCourseFiles.as_view(), name='add_courseFiles'),
    path('<slug:course_slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<slug:course_slug>/student', views.CourseDetailViewStudent.as_view(),
                       name='course_detailStudent'),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EdGeniusApp/forms.py
from .models import NewUser, Courses
from django.contrib.auth.forms import UserCreationForm
from django import forms


class SignUpForm(UserCreationForm):
    class Meta:
        model = NewUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'user_type')


class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ['course_name', 'description', 'course_image', 'course_tag', 'instructor',
                  'course_video', 'course_files']

EdGeniusApp/views.py
from datetime import date

from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views import View

from EdGeniusApp.decorators import redirect_if_logged_in
from EdGeniusApp.mixins import RedirectIfLoggedInMixin
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from .forms import SignUpForm, CoursesForm
from .models import NewUser, Student, Courses, Attendance, Grades, CourseEnrolled
from django.core.exceptions import ValidationError
from EdGenius import settings
import stripe
from django.contrib.auth.models import User, Group
from django.db.models import Q

stripe.api_key = settings.STRIPE_SECRET_KEY


class Index(TemplateView):
    template_name = 'EdGeniusApp/index.html'
    
class LoginInterfaceView(RedirectIfLoggedInMixin, LoginView):
    template_name = 'EdGeniusApp/login.html'

    def form_valid(self, form):
        # Call the parent class's form_valid method to perform the default login action
        response = super().form_valid(form)

        # Now, you can set the session data
        self.request.session['username'] = self.request.user.username
        self.request.session['first_name'] = self.request.user.first_name
        self.request.session['email'] = self.request.user.email
        # You can store any other user-specific data you need in the session.

        return response

    def get_success_url(self):
        success_url = super().get_success_url()

        # Get the user_type of the logged-in user from the database
        try:
            user_type = NewUser.objects.get(username=self.request.user.username).user_type
        except NewUser.DoesNotExist:
            user_type = None

        if user_type == "Student":
            membership = Student.objects.get(email=self.request.user.email).membership
            student = Student.objects.get(user__username=self.request.user.username)
            if membership == "Gold":
                self.request.session['membership'] = "Gold"
                # gold_courses = Courses.objects.filter(course_tag='Gold')
                gold_courses = Courses.objects.filter(Q(course_tag='Gold') | Q(course_tag='Silver') | Q(course_tag='Bronze'))
                for course in gold_courses:
                    CourseEnrolled.objects.get_or_create(student=student, course=course)
                return '/shomepage/'
            elif membership == "Silver":
                self.request.session['membership'] = "Silver"
                # silver_courses = Courses.objects.filter(course_tag='Silver')
                silver_courses = Courses.objects.filter(Q(course_tag='Silver') | Q(course_tag='Bronze'))
                for course in silver_courses:
                    CourseEnrolled.objects.get_or_create(student=student, course=course)
                return '/shomepage/'
            elif membership == "Bronze":
                self.request.session['membership'] = "Bronze"
                bronze_courses = Courses.objects.filter(course_tag='Bronze')
                for course in bronze_courses:
                    CourseEnrolled.objects.get_or_create(student=student, course=course)
                return '/shomepage/'
            else:
                return '/payment/'

        elif user_type == "Instructor":
            return '/ihomepage/'
        else:
            raise ValidationError('You are not a registered Student or Instructor')


class StudentHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'EdGeniusApp/student_homepage.html'

    def get(self, request, *args, **kwargs):
        username = request.session.get('username', None)
        first_name = request.session.get('first_name', None)
        course_list = CourseEnrolled.objects.filter(student__user__username=username)
        course_data_list=[]
        for course in course_list:
            course_detail = Courses.objects.get(course_name=course.course)
            course_data = {
                'id': course_detail.id,
                'course_name': course_detail.course_name,
                'instructor': course_detail.instructor,
                'description': course_detail.description,
                'course_image': course_detail.course_image,
                'course_tag': course_detail.course_tag,
                'slug': course_detail.slug,
                'course_video': course_detail.course_video,
                'course_files': course_detail.course_files
            }
            # Append the course data dictionary to the course_data_list
            course_data_list.append(course_data)
        context = {'first_name': first_name, 'course_data_list':course_data_list }
        return render(request, self.template_name, context)


class InstructorHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'EdGeniusApp/instructor_homepage.html'

    def get(self, request):
        first_name = request.session.get('first_name', None)
        course_list = Courses.objects.filter(instructor=request.user.id)
        return render(request, 'EdGeniusApp/instructor_homepage.html', {'course_list': course_list, 'first_name': first_name})


class LogoutInterfaceView(LoginRequiredMixin, LogoutView):
    template_name = 'EdGeniusApp/index.html'


class AuthorizedView(LoginRequiredMixin, TemplateView):
    template_name = 'EdGeniusApp/authorized.html'
    login_url = '/EdGeniusApp/login.html'


@redirect_if_logged_in
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            # load the profile instance created by the signal
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user_type = form.cleaned_data.get('user_type')

            # login user after signing up
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)

            if user_type == "Student":
            # redirect user to student home page
                return redirect('EdGeniusApp:payment')
            elif user_type == "Instructor":
                return redirect('EdGeniusApp:instructor_home')
            else:
                raise ValidationError("You are not a registered Student or Instructor")
    else:
        form = SignUpForm()
    return render(request, 'EdGeniusApp/signup.html', {'form': form})


class PasswordResetInterfaceView(PasswordResetView):
    template_name = 'EdGeniusApp/password_reset_form.html'
    email_template_name = 'EdGeniusApp/password_reset_email.html'
    success_url = reverse_lazy("EdGeniusApp:password_reset_done")


@login_required
def handle_payment_success(request):
    if request.method == 'POST':
        username = Student.objects.get(user__username=request.user.username)
        response = request.POST# Assuming you are receiving the Razorpay response here
        membership_type = request.POST.get('membership_type')  # Retrieve the membership type from the payment form
        username.membership_type = membership_type
        username.save(update_fields=['membership_type'])

        return JsonResponse({'message': 'Payment successful!'})
    return JsonResponse({'message': 'Invalid request.'}, status=400)


@login_required
def student_attendance(request, course_name):

    student_list = Student.objects.filter(courseenrolled__course__course_name=course_name)

    if request.method == 'POST':
        # student_instance = Student.objects.filter(user__username=request.session.get('username',None)).first()
        student_instance = Student.objects.filter(firstname=request.POST.get('firstname')).first()
        # student_instance = Student.objects.filter(filter(firstname=request.POST.get('fname'))).first()
       
        
        course_instance = Courses.objects.filter(course_name=course_name).values('id').first()
        course_id = course_instance['id']
        username = student_instance
        attendance = request.POST.get('attendance')

        up_attend = Attendance(
            student=username,
            course_id=course_id,
            attendance=attendance,
            date=date.today()
        )
        up_attend.save()
        return render(request,'EdGeniusApp/attendance.html', {'student_list': student_list, 'course_name': course_name})
    return render(request, 'EdGeniusApp/attendance.html', {'student_list': student_list, 'course_name': course_name})


@login_required
def my_courses(request):
    return render(request, 'EdGeniusApp/my_courses.html')


@login_required
def update_attendance(request,course_name):
    student_list = Student.objects.filter(courseenrolled__course__course_name=course_name)

    if request.method == 'POST':
        student_instance = Student.objects.get(user__username=request.session.get('username', None)).first()
        course_instance = Courses.objects.filter(course_name=course_name).values('id').first()
        course_id = course_instance['id']
        username = student_instance
        print(username)
        print(course_id)
        attendance = request.POST.get('attendance')

        up_attend = Attendance(
            student=username,
            course_id=course_id,
            attendance=attendance,
            date=date.today()
        )
        up_attend.save()
        return render(request, f'EdGenius/attendance.html/{course_name}', {'student_list': student_list})
    return render(request, f'EdGeniusApp/attendance.html/{course_name}', {'student_list': student_list})


# fetching attendance for course wise
@login_required
def fetch_attendance(request, course_name):

EdGeniusApp/templates/EdGeniusApp/base.html
<!DOCTYPE html>
{% load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
            integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I"
            crossorigin="anonymous"
    />
    <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
            integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
            crossorigin="anonymous"
    ></script>
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    <title> EdGenius - {% block title %} Welcome! {% endblock %}</title>
</head>
<body style="@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@500&display=swap'); font-family: 'Rubik', sans-serif;">
    <nav class="navbar navbar-dark" style="background: #22252A;">
        <div class="ms-auto">
            {% if user.is_authenticated %}
                <a href="{% url 'EdGeniusApp:student_home'%}" class="btn btn-outline-light me-1"> My courses</a>
                <a href="{% url 'EdGeniusApp:logout' %}" class="btn btn-outline-light me-1">Logout</a>
            {% else %}
                <a href="{% url 'EdGeniusApp:login' %}" class='btn btn-outline-light me-1'>Login</a>
                <a href="{% url 'EdGeniusApp:signup' %}" class='btn btn-outline-light me-1'>Signup</a>
            {% endif %}
        </div>
    </nav>

    <div class="my-5 text-center container">
        <h1>{% block myhdg %}
        {% endblock %}</h1>
        {% block body_block %}
        {% endblock %}
    </div>
<script>
    var sessionTimeout = {{ request.session.get_expiry_age }};
    var inactivityWarning = sessionTimeout - (60 * 5);

    setTimeout(function() {
        alert('You will be logged out due to inactivity in 5 minutes.');
    }, inactivityWarning * 1000);

    setTimeout(function() {
        window.location.href = '{% url "EdGeniusApp:logout" %}';
    }, sessionTimeout * 1000);
</script>
</body>
</html>

EdGeniusApp/templates/EdGeniusApp/check_student_grades.html
{% extends 'EdGeniusApp/base_instructor.html' %}
{% block title %}
    Check Student Grades
{% endblock %}

{% block body_block %}
<div class="container mt-5">
      <h1>Displaying Grades for {{ course_name }} Course</h1>
    </div>

    {% if student_list %}
    <div class="container mt-3">
      <label>Select a Student to view their Grades</label>
      {# action="{% url 'myapp1:fetchstudent' %}"#}
      <form action="{% url 'EdGeniusApp:check_student_grades' course_name %}" method="get">
        <select name="select-student-grades-dropdown">
          {% for student in student_list %}
              {% if student.email == student_email %}
                <option selected value="{{ student.email }}">{{ student.firstname }} {{ student.lastname }} </option>
              {% else %}
                 <option value="{{ student.email }}"> {{ student.firstname }} {{ student.lastname }} </option>
              {% endif %}
          {% endfor %}
        </select>
        <input type="submit" name="button" value="Search" />
      </form>
    </div>

    {% endif %}
    {% if individual_student_grades %}
    <div class="container mt-5">
      {% if student_name %}
      <h4>Student Name: {{ student_name }}</h4>
      {% endif %}
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>Grade Item</th>
              <th>Grade</th>
              <th>Feedbacks</th>
            </tr>
          </thead>
          <tbody>
            {% for student in individual_student_grades %}
            <tr>
              <td>{{ student.gradeItem }}</td>
              <td>{{ student.grade }}</td>
              <td>{{ student.feedback }}</td>

              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}

{% endblock %}

EdGeniusApp/templates/EdGeniusApp/course_detail.html
{% extends 'EdGeniusApp/base_instructor.html' %}

{% block title %}
Course Details - {{ course.course_name }}
{% endblock %}

{% block body_block %}

{#<div class="all-btns">#}
{#    <a href="{% url 'EdGeniusApp:add_courseFiles' course.slug %}" class="btn btn-primary">Add Course Files</a>#}
{#    <a href="{% url 'EdGeniusApp:index' %}" class="btn btn-primary">Take Attendance</a>#}
{#    <a href="{% url 'EdGeniusApp:index' %}" class="btn btn-primary">Show Attendance</a>#}
{#    <a href="{% url 'EdGeniusApp:index' %}" class="btn btn-primary">Input Grades</a>#}
{#    <a href="{% url 'EdGeniusApp:index' %}" class="btn btn-primary">Show Grades</a>#}
{#</div>#}
<br>
<h2>{{ course.course_name}}</h2>
<a href="{% url 'EdGeniusApp:student_attendance' course.course_name %}" class="btn btn-outline-light me-1" style="background: #3F88C5"> Update attendance</a>
<a href="{% url 'EdGeniusApp:fetch_attendance' course.course_name %}" class="btn btn-outline-light me-1" style="background: #3F88C5"> Check attendance</a>
<a href="{% url 'EdGeniusApp:grades_provider' course.course_name%}" class="btn btn-outline-light me-1" style="background: #3F88C5"> Provide Grades</a>
<a href="{% url 'EdGeniusApp:check_student_grades' course.course_name%}" class="btn btn-outline-light me-1" style="background: #3F88C5"> Check Grades</a>
<br>
<br>
<iframe width="800" height="400"
src="{{course.course_video}}">
</iframe>
<h1>Course Material</h1>
{% for course_file in course.course_files.all %}
  <h2><a href="{{ course_file.course_file.url }}" class="btn btn-outline-light me-1" style="background: #3F88C5">{{course.course_name}} File {{ forloop.counter }}</a></h2>
{% endfor %}
<!-- Display other course details here -->
{% endblock %}

EdGeniusApp/templates/EdGeniusApp/course_detailStudent.html
{% extends 'EdGeniusApp/base.html' %}

{% block title %}
Course Details - {{ course.course_name }}
{% endblock %}

{% block body_block %}
<h2>{{ course.course_name}}</h2>
<br>
<h3>Created by: {{ course.instructor}}</h3>
    <a href="{% url 'EdGeniusApp:my_attendance' course.course_name %}" class="btn btn-outline-light me-1" style="background: #3F88C5"> View My attendance</a>
    <a href="{% url 'EdGeniusApp:my_grades' course.course_name%}" class="btn btn-outline-light me-1" style="background: #3F88C5"> View My Grades</a>
<br>
<iframe width="800" height="400"
src="{{course.course_video}}">
</iframe>
{% for course_file in course.course_files.all %}
  <h2><a href="{{ course_file.course_file.url }}" class="btn btn-outline-light me-1" style="background: #3F88C5">{{course.course_name}} File {{ forloop.counter }}</a></h2>
{% endfor %}

{% endblock %}

EdGeniusApp/templates/EdGeniusApp/fetch_attendance.html
{% extends 'EdGeniusApp/base_instructor.html' %}
{% block title %}
Fetch Attendance
{% endblock %}

{% block body_block %}

 <div class="container mt-5">
      <h1>Displaying Attendance for {{ course_name }} Course</h1>
    </div>

    {% if student_list %}
        <div class="container mt-5">
        <label>Attendance</label>
{#    action="{% url 'myapp1:fetchstudent' %}"#}
        <form action="{% url 'EdGeniusApp:fetchstudent' course_name%}" method="get">
            <select name="select-student-name-dropdown">
                {% for student in student_list %}
                    {% if student.email ==  student_email %}
                        <option selected value="{{ student.email }}">{{ student.firstname }} {{ student.lastname }}</option>
                    {% else %}
                        <option value="{{ student.email }}">{{ student.firstname }} {{ student.lastname }}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <input type="submit" name="button" value="Search">
        </form>
        </div>
    {% endif %}


    {% if individual_student %}
        <div class="container mt-2">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <th>Firstname</th>
                        <th>Lastname</th>
                        <th>Email</th>
                        <th>Attendance</th>
                        <th>Date</th>

                    </tr>
                    </thead>
                <tbody>
                {% for student in individual_student %}
                    <tr>
                    <td>{{ student.student.firstname}}</td>
                    <td>{{ student.student.lastname }}</td>
                    <td>{{ student.student.email }}</td>
                    <td>{{ student.attendance }}</td>
                    <td>{{ student.date }}</td>

                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock %}

EdGeniusApp/templates/EdGeniusApp/index.html
{% extends 'EdGeniusApp/base.html' %}
{% block title %}
    EdGenius
{% endblock %}
{% load static %}

{% block body_block %}
<div class="main-body">
    <div class="upper-container">
       
        <img id="index2" src="{% static 'index2.svg' %}" style="width: 25rem;">
    </div>
    <br>
    <div class="lower-container"  style="width: 50rem; margin-left: 20%; font-size: 1.5rem;">
        <h1>EdGenius</h1>
        <p>Welcome to our cutting-edge web platform designed to foster interactive and immersive learning experiences for students across diverse subjects. Our user-friendly application not only facilitates skill development but also serves as a comprehensive tool for teachers to efficiently manage their courses and students.

        </p>
    </div>
</div>
{% endblock %}

EdGeniusApp/templates/EdGeniusApp/password_reset_complete.html
{%extends 'EdGeniusApp/base.html' %}
{% block title %}
Forgot Password Complete
{% endblock %}

{%block body_block%}

<div>
	<p>Your password has been changed successfully. Please <a href="{% url 'EdGeniusApp:login' %}">Login</a></p>
</div>

{%endblock%}

EdGeniusApp/templates/EdGeniusApp/password_reset_confirm.html
{% extends 'EdGeniusApp/base.html' %}
{% block title %}
Forgot Password Confirm
{% endblock %}
{% block body_block %}
    <form method="POST" style="text-align: center; margin:auto; width:50%">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>

	  {% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
                <br>
                <br>
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small>
	        	{% endif %}
		{% endfor %}

	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
{% endblock %}

EdGeniusApp/templates/EdGeniusApp/payment.html
{% extends 'EdGeniusApp/base.html' %}
{% block title %}
Membership
{% endblock %}
{% block myhdg %}
Membership Options
{% endblock %}
{% block body_block %}
    <h4> Please select the membership as per your requirement: </h4>
<br>
<br>
<br>
 <div class="container mt-5">
        <h1>Choose a Membership</h1>

    </div>
     <div class="container mt-5">

         <div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-3">
        <div class="card h-100" id="gold">
          <div class="card-body">
            <h4 class="card-title" style="color: #3F88C5">Gold</h4>
              <h5> Price: 80 CAD</h5>
              <p class="card-text">Get access to advanced courses and LinkedIn Learning..</p>
              <form action="{% url 'EdGeniusApp:charge' 8000 %}" method="post">
             {% csrf_token %}
             <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                 data-key = "{{ key }}"
                 data-description ="Payment Gateway"
                 data-amount="8000"
                 data-locale="auto" >

            </script>

              </form>
          </div>
        </div>
    </div>

    <div class="col mb-3">
        <div class="card h-100" id="silver">
          <div class="card-body">
            <h4 class="card-title" style="color: #3F88C5">Silver</h4>
              <h5> Price: 50 CAD</h5>
            <p class="card-text">Get access to available courses..</p>
              <div class="mt-4">
               <form action="{% url 'EdGeniusApp:charge' 5000 %}" method="post">
             {% csrf_token %}
             <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                 data-key = "{{ key }}"
                 data-description ="Payment Gateway"
                 data-amount="5000"
                 data-locale="auto" >

            </script>

              </form>
              </div>
          </div>
        </div>
    </div>

    <div class="col mb-3">
        <div class="card h-100" id="bronze">
          <div class="card-body">
            <h4 class="card-title" style="color: #3F88C5">Bronze</h4>
              <h5> Price: 30 CAD</h5>
                <p class="card-text">Get access to limited courses..</p>
              <div class="mt-4">
                  <form action="{% url 'EdGeniusApp:charge' 3000 %}" method="post" >
             {% csrf_token %}
             <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                 data-key = "{{ key }}"
                 data-description ="Payment Gateway"
                 data-amount="3000"
                 data-locale="auto" >

             </script>

              </form>
              </div>
          </div>
        </div>
    </div>
</div>
     </div>
{% endblock %}

EdGeniusApp/templates/EdGeniusApp/student_homepage.html
{% extends 'EdGeniusApp/base.html' %}
{% block title %}
Home
{% endblock %}

{% block body_block %}
<h1> Hello {{ first_name }} </h1>

        {% if course_data_list %}

        <h2> Your Courses</h2>

          <div class="card-container">

        {% for course in course_data_list %}
        <div class="cards-collection">
            <div class="card text-white bg-dark mb-3" style="width: 18rem; height:25rem">
                <img class="card-img-top" src="http://127.0.0.1:8000/{{course.course_image}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{course.course_name}} ({{ course.course_tag }})</h5>
                    <p class="card-text">{{course.description}}</p>
                    <p class="card-text">{{course.instructor}}</p>
                    <!-- <a href="http://127.0.0.1:8000/{{course.course_pdf}}" class="btn btn-primary">pdf</a> -->
                    <a href="{% url 'EdGeniusApp:course_detailStudent' course.slug %}" class="btn btn-outline-light me-1" style="background: #3F88C5">Open Course</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}

        {% endif %}
    </div>


<style>


    .card-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;


    }
   .cards-collection{
      margin: 1rem;
    }

    /* Add any other styling you need */
</style>
{% endblock %}